export const SELECT_LANGUAGE = 'select_language';

export const USER_REGISTER_UPDATE = 'user_register_update';
export const USER_CREATE = 'user_create';

export const USER_LOGIN_UPDATE = 'user_login_update';


export const APP_SET_USER_DATA = 'APP_SET_USER_DATA';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const PASSWORD_CHANGE_UPDATE = 'PASSWORD_CHANGE_UPDATE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const SET_PACK_DATA = 'SET_PACK_DATA';
export const SET_STORE_DATA = 'SET_STORE_DATA';
export const SET_SELECTED_STORE_DATA = 'SET_SELECTED_STORE_DATA';
export const SET_CURRENT_PACK_DATA = 'SET_CURRENT_PACK_DATA';
export const SET_CURRENT_SITE_DATA = 'SET_CURRENT_SITE_DATA';
export const SET_DOWNLOAD_QUEUE = 'SET_DOWNLOAD_QUEUE';
export const SET_INTRODUCTION_DATA = 'SET_INTRODUCTION_DATA';
export const SET_LANGUAGE_DATA = 'SET_LANGUAGE_DATA';
export const CLEAR_DATA = 'CLEAR_DATA';
export const SET_CURRENT_AUDIO = 'SET_CURRENT_AUDIO';
export const SHOW_AUDIO_PLAYER = 'SHOW_AUDIO_PLAYER';
export const SET_PLAYER_VALUES = 'SET_PLAYER_VALUES';
export const SET_INTRODUCTION_AUDIO_DOWNLOAD_DATA = 'SET_INTRODUCTION_AUDIO_DOWNLOAD_DATA';
export const SET_SITES_AUDIO_DOWNLOAD_DATA = 'SET_SITES_AUDIO_DOWNLOAD_DATA';
