import { StyleSheet } from 'react-native';
import Constant from './constants'


export default StyleSheet.create({
    imgSize1: {height: null, width: null},
    imgSize0: {top: 0, bottom: 0, left: 0, right: 0},
    imgContainer: { height: 150, width: 150 },
    transparent: { color: 'rgba(0, 0, 0, 0.0)' },
    transparentBackground: { backgroundColor: 'rgba(0, 0, 0, 0.0)' },
    blackBackground: { backgroundColor: 'rgba(0, 0, 0, 0.5)' },
    borderGrayColor: {backgroundColor: 'rgb(202,204,205)'},
    color000: { color: '#FFF' },
    color50: { color: '#FAFAFA' },
    color100: { color: '#F5F5F5' },
    color200: { color: '#EEEEEE' },
    color300: { color: '#E0E0E0' },
    color400: { color: '#BDBDBD' },
    color500: { color: '#9E9E9E' },
    color600: { color: '#757575' },
    color700: { color: '#616161' },
    color800: { color: '#424242' },
    color100: { color: '#000000' },
    colorP1: { color: '#10E895' },
    colorP2: { color: '#1FB37A' },
    colorP3: { color: '#e74c3c' },
    colorP4: { color: '#2ecc71' },
    colorP5: { color: '#178CFC' },
    colorP6: { color: '#feb92c' },
    colorP7: { color: '#8462eb' },
    colorS3: { color: '#ea6153' },
    colorS4: { color: '#40d47e' },
    colorS5: { color: '#4990E2' },
    colorS6: { color: '#feca5f' },
    colorS7: { color: '#9679ee' },
    colorA3: { color: '#ed7669' },
    colorA4: { color: '#7ee2a8' },
    colorA5: { color: '#6ba5e7' },
    colorA6: { color: '#fed278' },
    colorA7: { color: '#b9a6f4' },
    colorA8: { color: '#1F1F1F' },
backColor: {backgroundColor: 'rgb(232,232,232)'},
    themeColor: {backgroundColor: '#FFCC29'},
    themeFontColor: {color: '#FFCC29'},
    navColor: {backgroundColor: '#1F1F1F'},
    bg0: {backgroundColor: 'rgb(236,235,242)'},
    bg000: { backgroundColor: '#fff' },
    bg100: { backgroundColor: '#F5F5F5' },
    bg200: { backgroundColor: '#EEEEEE' },
    bg300: { backgroundColor: '#E0E0E0' },
    bg400: { backgroundColor: '#BDBDBD' },
    bg500: { backgroundColor: '#9E9E9E' },
    bg600: { backgroundColor: '#757575' },
    bg700: { backgroundColor: '#616161' },
    bg800: { backgroundColor: '#424242' },
    bgGray: { backgroundColor: '#E8E8E8' },
    bgTile1: { backgroundColor: '#3498db' },
    bgP1: { backgroundColor: '#10E895' },
    bgP2: { backgroundColor: '#1FB37A' },
    bgP3: { backgroundColor: '#e74c3c' },
    bgP4: { backgroundColor: '#2ecc71' },
    bgP5: { backgroundColor: '#178CFC' },
    bgP6: { backgroundColor: '#feb92c' },
    bgP7: { backgroundColor: '#8462eb' },
    bgS3: { backgroundColor: '#ea6153' },
    bgS4: { backgroundColor: '#40d47e' },
    bgS5: { backgroundColor: '#4990E2' },
    bgS6: { backgroundColor: '#feca5f' },
    bgS7: { backgroundColor: '#9679ee' },
    bgA3: { backgroundColor: '#ed7669' },
    bgA4: { backgroundColor: '#7ee2a8' },
    bgA5: { backgroundColor: '#6ba5e7' },
    bgA6: { backgroundColor: '#fed278' },
    bgA7: { backgroundColor: '#b9a6f4' },
    border000: { borderColor: '#FFFFFF' },
    border200: { borderColor: '#EEEEEE' },
    border300: { borderColor: '#E0E0E0' },
    borderP1: { borderColor: '#10E895' },
    borderP2: { borderColor: '#1FB37A' },
    borderP3: { borderColor: '#e74c3c' },
    borderP4: { borderColor: '#2ecc71' },
    borderP5: { borderColor: '#178CFC' },
    borderP6: { borderColor: '#feb92c' },
    borderError: { borderColor: '#FF2000' },
    borderWidth1: { borderWidth: 1 },
    borderWidth105: { borderWidth: 1.5 },
    borderWidth2: { borderWidth: 2 },
    borderBWidth1: { borderBottomWidth: 1},
    borderBWidth07: { borderBottomWidth: 0.7},
    borderBWidth2: { borderBottomWidth: 2},
    borderRWidth1: { borderRightWidth: 1},
    borderTWidth1: { borderTopWidth: 1},
    borderLWidth1: { borderLeftWidth: 1},
    shadow1: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1 },
    shadow2: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2 },
    shadow3: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3 },
    shadow4: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.4 },
    shadow5: { shadowColor: '#000000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.5 },
    container: {
        flex: 1,
        backgroundColor: '#f9fafa'
    },
    contentHeader: {
        paddingTop: 28
    },
    contentHeaderText: {
        fontSize: 15,
        fontWeight: '600'
    },
    centered: {
        alignSelf: 'center',
        marginTop: 10,
        marginBottom: 10
    },
    centerChildren: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    spaceChildren: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'space-between',
    },
    selfLeft: {
        alignSelf: 'flex-start',
        marginTop: 10,
        marginBottom: 10
    },
    pt05: { paddingTop: 5 },
    pt06: { paddingTop: 6 },
    pt07: { paddingTop: 7 },
    pt1: { paddingTop: 10 },
    pt102: { paddingTop: 12 },
    pt105: { paddingTop: 15 },
    pt2: { paddingTop: 20 },
    pt3: { paddingTop: 30 },
    pt4: { paddingTop: 40 },
    pb0: { paddingBottom: 0 },
    pb05: { paddingBottom: 5 },
    pb06: { paddingBottom: 6 },
    pb07: { paddingBottom: 7 },
    pb1: { paddingBottom: 10 },
    pb105: { paddingBottom: 15 },
    pb2: { paddingBottom: 20 },
    pb3: { paddingBottom: 30 },
    pb4: { paddingBottom: 40 },
    pr05: { paddingRight: 5 },
    pr08: { paddingRight: 8 },
    pr1: { paddingRight: 10 },
    pr105: { paddingRight: 15 },
    pr2: { paddingRight: 20 },
    pr3: { paddingRight: 30 },
    pr4: { paddingRight: 40 },
    pl0: { paddingLeft: 0 },
    pl05: { paddingLeft: 5 },
    pl08: { paddingLeft: 8 },
    pl1: { paddingLeft: 10 },
    pl105: { paddingLeft: 15 },
    pl2: { paddingLeft: 20 },
    pl3: { paddingLeft: 30 },
    pl4: { paddingLeft: 40 },
    mt0: { marginTop: 0 },
    mt05: { marginTop: 5 },
    mt1: { marginTop: 10 },
    mt103: { marginTop: 13 },
    mt105: { marginTop: 15 },
    mt2: { marginTop: 20 },
    mt3: { marginTop: 30 },
    mt4: { marginTop: 40 },
    mt5: { marginTop: 50 },
    mt6: { marginTop: 60 },
    mt7: { marginTop: 70 },
    mt8: { marginTop: 80 },
    mb0: { marginBottom: 0 },
    mb05: { marginBottom: 5 },
    mb1: { marginBottom: 10 },
    mb105: { marginBottom: 15 },
    mb2: { marginBottom: 20 },
    mb3: { marginBottom: 30 },
    mb4: { marginBottom: 40 },
    mb5: { marginBottom: 50 },
    mb6: { marginBottom: 60 },
    mb7: { marginBottom: 70 },
    mb8: { marginBottom: 80 },
    ml0: { marginLeft: 0 },
    ml05: { marginLeft: 5 },
    ml08: { marginLeft: 8 },
    ml1: { marginLeft: 10 },
    ml105: { marginLeft: 15 },
    ml2: { marginLeft: 20 },
    ml3: { marginLeft: 30 },
    ml4: { marginLeft: 40 },
    ml5: { marginLeft: 35 },
    ml50: { marginLeft: 50 },
    ml8: { marginLeft: 80 },
    mr05: { marginRight: 5 },
    mr08: { marginRight: 8 },
    mr0: { marginRight: 0 },
    mr1: { marginRight: 10 },
    mr105: { marginRight: 15 },
    mr2: { marginRight: 20 },
    mr3: { marginRight: 30 },
    mr4: { marginRight: 40 },
    mr5: { marginRight: 50 },
    mr6: { marginRight: 60 },
    mr7: { marginRight: 70 },
    mr8: { marginRight: 80 },
    radius3: { borderRadius: 3 },
    radius5: { borderRadius: 5 },
    radius7: { borderRadius: 7 },
    radius15: { borderRadius: 15 },
    radiusRound: { borderRadius: 100 },
    radiusBL5: { borderBottomLeftRadius: 5 },
    radiusBR5: { borderBottomRightRadius: 5 },
    radiusTL5: { borderTopLeftRadius: 5 },
    radiusTR5: { borderTopRightRadius: 5 },
    gridSelectServicePrice: {
        fontWeight: '500',
        fontSize: 28
    },
    emptyStateText: {
        paddingLeft: 40,
        paddingRight: 40
    },
    i: { fontStyle: "italic" },
    u: { textDecorationLine: "underline" },
    tl: { textAlign: "left" },
    tc: { textAlign: "center" },
    tr: { textAlign: "right" },
    tj: { textAlign: "justify" },
    "fheadline": { fontSize: 6*16 },
    "fsubheadline": { fontSize: 5*16, lineHeight: 78 },
    f1: { fontSize: 3*16, lineHeight: 46 },
    f1Height : { height: 55 },
    f2: { fontSize: 2.25*16},
    f205: { fontSize: 1.7*16},
    f3: { fontSize: 1.5*16},
    f305: { fontSize: 1.15*16 },
    f4: { fontSize: 1.25*16 },
    f405: { fontSize: 1.125*16 },
    f5: { fontSize: 1*16 },
    f505: { fontSize: .93*16 },
    f6: { fontSize: 0.875*16 },
    f605: { fontSize: 0.75*16 },
    fi5: { fontSize: 15 },
    normal: { fontWeight: 'normal' },
    b: { fontWeight: 'bold' },
    fw1: { fontWeight: '100' },
    fw2: { fontWeight: '200' },
    fw3: { fontWeight: '300' },
    fw4: { fontWeight: '400' },
    fw5: { fontWeight: '500' },
    fw6: { fontWeight: '600' },
    fw7: { fontWeight: '700' },
    fw8: { fontWeight: '800' },
    fw9: { fontWeight: '900' },
    lineh1: { lineHeight: 24 },
    lineh2: { lineHeight: 34 },
    ls1: { letterSpacing: .25 },
    colorMuted: { color: '#bbb'},
    relative: { position: 'relative' },
    absolute: { position: 'absolute' },
    flx1: { flex: 1 },
    flx2: { flex: 2 },
    flx3: { flex: 3 },
    flx4: { flex: 4 },
    flx5: { flex: 5 },
    flx6: { flex: 6 },
    flxCol: { flexDirection: 'column' },
    flxRow: { flexDirection: 'row' },
    flxWrap: { flexWrap: 'wrap' },
    flxNoWrap: { flexWrap: 'nowrap' },
    itemsStart: { alignItems: 'flex-start' },
    itemsCenter: { alignItems: 'center' },
    itemsEnd: { alignItems: 'flex-end' },
    itemsStretch: { alignItems: 'stretch' },
    selfStart: { alignSelf: 'flex-start' },
    selfCenter: { alignSelf: 'center' },
    selfEnd: { alignSelf: 'flex-end' },
    selfStretch: { alignSelf: 'stretch' },
    jcStart: { justifyContent: 'flex-start' },
    jcEnd: { justifyContent: 'flex-end' },
    jcCenter: { justifyContent: 'center' },
    jcBetween: { justifyContent: 'space-between' },
    jcAround: { justifyContent: 'space-around' },
    bottom1: { position: 'absolute', bottom: 0, left: 0, right: 0 },
    bottom2: { position: 'absolute', bottom: 0 },
    right1: { position: 'absolute', bottom: 12, right: 0 },
    left1: { position: 'absolute', right: 0 },
    placeholder1: { height: 100 },
    txtHeight30: { height: 25 },
    width30: { width: 30 },
    height30: { height: 30 },
    navHeight: {height: 54},
    height1: {height: 1},
    height10: {height: 10},
    iconWidth: { width: 50 },
   Width7: { width: 230 },
    iconHeight: { height: 50 },
    errorIcon: { position: 'absolute', top: 0, left: 0 },
    errorText: { marginLeft: 46 },
    chatUnreadCircle: { width: 12, height: 12, borderRadius: 100/2, backgroundColor: '#e74c3c' },
    listCities: { backgroundColor: '#fff' },
    listItemCities: { borderBottomWidth: 0 },
    listItemCitiesText: { color: '#ddd', fontSize: 46, fontWeight: '500' },
    vehicleModal: { height: 260 },
    brandContainer: { position: 'absolute', top: 35, right: 20, zIndex: -1 },
    brandImage: { height: 50.3333, width: 63.6666 },
    brandImageNavContainer: { position: 'absolute', bottom: 7, left: 0, right: 0, justifyContent: 'center', alignItems: 'center' },
    brandImageNav: { height: 37, width: 140 },
    brandImageNav1: { height: 25, width: 93.5 },
    brandText: { opacity: 0.7 },
    bookingNavigationContainer: { backgroundColor: '#fff', borderTopWidth: 1, borderColor: '#EEEEEE', paddingTop: 15, zIndex: 2 },
    paymentCardIcon: { width: 60 , height: 36 },
    profileUserImgPlaceholder: { width: 70 , height: 70 },
    // Dashboard Tech status
    dashboardStatusIconWidth: { width: 30 },
    width45: { width: 45 },
    barVerticalBottom: { left: 6.2, bottom: 0, top: 50, width: 1, backgroundColor: '#DEDEDE', position: 'absolute'},
    barVerticalTop: { left: 6.2, bottom: 50, top: 0, width: 1, backgroundColor: '#DEDEDE', position: 'absolute'},
    barVerticalIcon: { marginTop: 20 },
    scH: {height: Constant.screenWidth},
    scH2: {height: Constant.screenWidth-20},
    scH3: {height: Constant.screenWidth-80},
    screenHeightby2: {height: Constant.screenWidth*2.2},
    scW: {width: Constant.screenWidth},
    pad10: {padding: 10},
    pad0: {padding: 0},
    });
