
import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
  //1 lang...
  "en-US":{
    in:"In the",
    buddha:"Buddha's",
    footsteps:"Footsteps",
    register: 'Register',
    signin: 'Sign In',
    email: 'Email',
    newPassword: 'New Password',
    password: 'Password',
    createpassword: 'Create Password',
    confirmpassword: 'Confirm Password',
    couponcode: 'Coupon Code',
    home: 'Home',
    store:'Store',
    site:'All Sites',
    loading: 'Loading stores...',
    Footsteps: 'Footsteps',
    settings: 'Settings',
    forgot: 'Forgot Password?',
    forgotText: 'We will send password on your email',
    cleardata: 'Clear Data',
    changelang: 'Change Language',
    changepass: 'Change Password',
    terms: 'Terms and Privacy Policy',
    signout: 'Sign Out',
    about: 'About',
    introduction: 'Introduction',
    nextSite: 'Next Site',
    selectLang: 'Select Language',
    update: 'Update',
    noData: 'No Data Available',
      myPacks:'My Packs',
      transcript: 'Transcript'
  },
  // 3 lang...
  en:{
    in:"en el",
    buddha:"Buda",
    footsteps:"pasos",
    register: 'Registro',
    signin: 'Registrarse',
    email: 'Email',
    newPassword: 'nueva contraseña',
    password: 'Contraseña',
    createpassword: 'Crear contraseña',
    confirmpassword: 'Confirmar contraseña',
    couponcode: 'Código promocional',
    home: 'Casa',
    store: 'Almacenar',
    site:'Todos los sitios',
    loading: 'Cargando tiendas...',
    Footsteps: 'Pasos',
    settings : 'Ajustes',
    forgot: '¿Se te olvidó tu contraseña?',
    forgotText: 'Enviaremos una contraseña en su correo electrónico',

    cleardata: 'Borrar datos',
    changelang: 'Cambiar idioma',
    changepass: 'Cambia la contraseña',
    terms: 'Términos y Política de Privacidad',
    signout: 'Desconectar',
    about: 'Acerca de',
    introduction: 'Introducción',
    nextSite: 'Siguiente Sitio',
    selectLang: 'Seleccione el idioma',
    update: 'Actualizar',
    noData: 'datos no disponibles',
      myPacks:'Mis paquetes',
      transcript: 'Transcripción'

  },
  // 2 lang....
  it: {
    in:"dans le",
    buddha:"Bouddha",
    footsteps:"trace de pas",
    register: 'Registre',
    signin: 'Se connecter',
    email: 'Email',
    newPassword: 'nouveau mot de passe',
    password: 'Mot de passe',
    createpassword: 'Créer un mot de passe',

    confirmpassword: 'Confirmez le mot de passe',
    couponcode: 'Code de coupon',
    home: 'Accueil',
    store:'le magasin',
    site: 'Tous les sites',
    loading: 'Chargement des magasins...',
    Footsteps: 'trace de pas',
    settings: 'Paramètres',
    forgot: 'Mot de passe oublié?',
    forgotText: 'Nous vous enverrons un mot de passe sur votre courriel\n',

    cleardata: 'Effacer les données',
    changelang: 'Changer de langue',
    changepass: 'Changer le mot de passe',
    terms: 'Termes et politique de confidentialité',
    signout: 'Déconnexion',
    about: 'Sur',
    introduction: 'Introduction',
    nextSite: 'Site suivant',
    selectLang: 'Choisir la langue',
    update: 'Mettre à jour',
    noData: 'pas de données disponibles',
      myPacks:'Mes Packs',
      transcript: 'Transcript'

  },
  // 4 lang....
  rs: {
    in:"в",
    buddha:"Будда",
    footsteps:"шаги",
    register: 'регистр',
    signin: 'Войти в систему',
    email: 'Эл. адрес',
    newPassword: 'новый пароль',
    password: 'пароль',
    createpassword: 'Придумайте пароль',

    confirmpassword: 'Подтвердите Пароль',
    couponcode: 'код купона',
    home: 'Главная',
    store:'хранить',
    site: 'Все сайты',
    loading: 'Загрузка магазинов ...',
    Footsteps: 'шаги',
    settings: 'настройки',
    forgot: 'Забыли пароль?',
    forgotText: 'Мы отправим вам пароль по электронной почте',

    cleardata: 'Очистить данные',
    changelang: 'Изменить язык',
    changepass: 'Изменить пароль',
    terms: 'Условия и политика конфиденциальности',
    signout: 'Выход',
    about: 'Около',
    introduction: 'Введение',
    nextSite: 'Следующий сайт',
    selectLang: 'Выберите язык',
    update: 'Обновить',
    noData: 'данные недоступны',
      myPacks:'Мои пакеты',
      transcript: 'расшифровка'


  },
  //5 lang....
  ch: {
    in:"在里面",
    buddha:"佛",
    footsteps:"步伐",
    register: '寄存器',
    signin: '签到',
    email: '电子邮件',
    newPassword: '新密码',
    password: '密码',
    createpassword: '创建密码',

    confirmpassword: '确认密码',
    couponcode: '优惠券代码',
    home: '家',
    store:'商店',
    site: '所有网站',
    loading: '加载商店...',
    Footsteps: '步伐',
    settings: '设置',
    forgot: '忘记密码？',
    forgotText: '我们将在您的电子邮件中发送密码',

    cleardata: '清除数据',
    changelang: '改变语言',
    changepass: '更改密码',
    terms: '条款和隐私政策',
    signout: '登出',
    about: '关于',
    introduction: '介绍',
    nextSite: '下一站',
    selectLang: '选择语言',
    update: '更新',
    noData: '无可用数据',
      myPacks:'我的包',
      transcript: '抄本'


  },
});

module.exports = strings;
